/** SQLite şemasında string olarak saklanır (Prisma enum yok) */
export const PipelineStage = {
  NEW_LEAD: "NEW_LEAD",
  REVIEWING: "REVIEWING",
  CONTACT_ATTEMPT: "CONTACT_ATTEMPT",
  UNREACHABLE: "UNREACHABLE",
  CONTACTED: "CONTACTED",
  QUALIFICATION_CALL: "QUALIFICATION_CALL",
  QUALIFIED: "QUALIFIED",
  UNQUALIFIED: "UNQUALIFIED",
  ZOOM_SCHEDULED: "ZOOM_SCHEDULED",
  ZOOM_DONE: "ZOOM_DONE",
  OFFER_MADE: "OFFER_MADE",
  FOLLOW_UP: "FOLLOW_UP",
  WON: "WON",
  LOST_NOT_NOW: "LOST_NOT_NOW",
  LOST_FOREVER: "LOST_FOREVER",
  NOT_NOW: "NOT_NOW",
  REACTIVATION: "REACTIVATION",
  BLACKLIST: "BLACKLIST",
} as const;

export const LeadSource = {
  WUFOO: "WUFOO",
  INSTAGRAM_DM: "INSTAGRAM_DM",
  WHATSAPP: "WHATSAPP",
  MANUAL: "MANUAL",
  REFERRAL: "REFERRAL",
  EMAIL: "EMAIL",
  WEBSITE: "WEBSITE",
} as const;

export const LeadTag = {
  NONE: "NONE",
  INCOMPLETE_LEAD: "INCOMPLETE_LEAD",
  QUALIFIED: "QUALIFIED",
  UNQUALIFIED: "UNQUALIFIED",
  IDEAL_CLIENT: "IDEAL_CLIENT",
  OPPORTUNITY: "OPPORTUNITY",
  FOLLOW_UP_NEEDED: "FOLLOW_UP_NEEDED",
} as const;

export const CallOutcome = {
  NO_ANSWER: "NO_ANSWER",
  CONTACTED: "CONTACTED",
  VOICEMAIL: "VOICEMAIL",
  CALLBACK_SCHEDULED: "CALLBACK_SCHEDULED",
} as const;

export const TaskType = {
  CALLBACK: "CALLBACK",
  FOLLOW_UP: "FOLLOW_UP",
  ZOOM_PREP: "ZOOM_PREP",
  CUSTOM: "CUSTOM",
} as const;

export const LeadCompleteness = {
  INCOMPLETE: "INCOMPLETE",
  COMPLETE: "COMPLETE",
} as const;
